<?php


namespace Model\Entity;

use Model\Entity\Interfaces\EntityInterface;

class Group extends Entity implements EntityInterface{
    private ?string $name;

    public function __construct(int $id = null, string $name = null)    {
        parent::__construct($id); // TODO: Change the autogenerated stub
    }

    /**
     * get the Name
     * @return string|null
     */
    public function getName(): ?string    {
        return $this->name;
    }

    /**
     * set the Name
     * @param string|null $name
     * @return Group
     */
    public function setName(?string $name): Group    {
        $this->name = $name;
        return $this;
    }

    /**
     * return all the value of object
     * @return array
     */
    public function getAllData(): array    {
        $array['id'] = $this->getId();
        $array['name'] = $this->getName();
        return $array;
    }
}